# Generated by Django 3.2.25 on 2024-08-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AgenceLuxe', '0001122_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='image/person-circle.svg', upload_to='img_userProfile', verbose_name='photo de profile'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('manager', 'Manager'), ('developeur', 'Developeur'), ('designer', 'Designer'), ('analyste', 'Analyste'), ('secretaire', 'Secretaire'), ('vigile', 'Vigile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
