# Generated by Django 3.2.25 on 2024-08-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenceLuxe', '1123_auto_20240805_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='cv',
            field=models.ImageField(default='image/person-circle.svg', upload_to='img_userCV', verbose_name='CV'),
        ),
    ]
